spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wallet_api
        username: wallet
        password: wallet

    jpa:
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true

server:
    servlet:
        context-path: /api/v1
