spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wallet_api
        username: wallet
        password: wallet

    data:
        redis:
            host: localhost
            port: 6379

    cache:
        type: redis
        redis:
            time-to-live: 24h

    kafka:
        bootstrap-servers: localhost:9092

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

        consumer:
            group-id: wallet-api
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: com.aidana.wallet_api.kafka.event

    jpa:
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true

server:
    servlet:
        context-path: /api/v1

logging:
    level:
        org.springframework.cache: TRACE
        org.springframework.data.redis: DEBUG
