spring.application.name=wallet-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_api
spring.datasource.username=wallet
spring.datasource.password=wallet
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:35a1bb68-a20b-4967-ae92-6846559aced1}
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=30
