spring.application.name=wallet-api
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_api
spring.datasource.username=wallet
spring.datasource.password=wallet
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:some-secret}
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=30
